name: Monitor ss-rust.sh

on:
  schedule:
    - cron: '0 0 * * *' # 每天UTC 0点
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Shanghai timezone
        run: sudo timedatectl set-timezone Asia/Shanghai
      - name: Download ss-rust.sh
        run: |
          curl -sSL -o ss-rust.sh https://raw.githubusercontent.com/xOS/Shadowsocks-Rust/refs/heads/master/ss-rust.sh
      - name: Commit and push if updated
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          if [[ `git status --porcelain ss-rust.sh` ]]; then
            git add ss-rust.sh
            git commit -m 'chore: update ss-rust.sh from upstream'
            git push
          else
            echo "No update detected."
          fi 
